---
name: Vault Action
author: Konstantinos Dichalas
description: |
  An action that helps you inderact with a vault instance.
  It can Authenticate using Github OIDC, read Secrets
  and even expose the Vault Token for later use.

inputs:
  url:
    description: The URL of the Vault instance
    required: true
  role:
    description: The Vault role to use for authentication
    required: false
    default: "github-action"
  jwt_claim:
    description: The JWT claim to use for authentication
    required: false
    default: github
  output_token:
    description: Output the Vault token
    required: false
    default: "false"
  secrets:
    description: A list of secrets to read from Vault
    required: false
    default: ""

runs:
  using: docker
  image: docker://ghcr.io/kdichalas/vault-action:v0.0.6