---
name: Simple Vault Action
author: Konstantinos Dichalas
description: |
  An action that helps you inderact with a Hashicorp Vault Instance

inputs:
  url:
    description: The URL of the Vault instance
    required: true
  role:
    description: The Vault role to use for authentication
    required: false
    default: "github-action"
  jwt_claim:
    description: The JWT claim to use for authentication
    required: false
    default: actor
  output_token:
    description: Output the Vault token
    required: false
    default: "false"
  secrets:
    description: A list of secrets to read from Vault
    required: false
    default: "empty"

runs:
  using: docker
  image: docker://ghcr.io/kdihalas/vault-action:v0.0.23
