name: Smoketest

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
jobs:
  run:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Import Secrets
        id: import-secrets
        uses: kdihalas/vault-action@main
        with:
          url: https://vault.kdichalas.net
          output_token: "true"
          secrets: |
            data/ci/aws id | AWS_ID;
            data/ci/aws secret | AWS_SECRET;
      - name: Print vault-token
        run: echo $VAULT_TOKEN
      - name: Print id and secret
        run: |
          echo $AWS_ID;
          echo $AWS_SECRET;