name: Tag new version

on:
  push:
    branches:
      - "main"
jobs:
  build:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install git-semver
        run: brew install mdomke/git-semver/git-semver
      - name: Check if commit includes version bump
        id: bump
        run: |
          echo target=$(git rev-list --max-count=1 --no-commit-header --format=%B HEAD | awk -F":" '{print $1}' | tr -d "\n\r" | grep -e "major\|minor\|patch") >> "$GITHUB_OUTPUT"
      - name: Get next version
        id: version
        run: |
          export TARGET_VAR="${{ steps.bump.outputs.target }}"
          export TARGET=${TARGET_VAR:-dev}
          echo next=$(git-semver -prefix v -target $TARGET) >> "$GITHUB_OUTPUT"
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.version.outputs.next }}",
              sha: context.sha
            })